/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    partners: Partner;
    certifications: Certification;
    'solution-categories': SolutionCategory;
    products: Product;
    'contact-submissions': ContactSubmission;
    users: User;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'solution-categories': SolutionCategoriesSelect<false> | SolutionCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL part. Lowercase letters, numbers and "-". Generated from the title when empty.
   */
  slug: string;
  layout: (
    | HeroBlock
    | ProblemShowcaseBlock
    | VideoShowcaseBlock
    | SolutionHighlightsBlock
    | ExpertiseBlock
    | FeatureGridBlock
    | LeadershipBlock
    | TeamStatsBlock
    | PartnersBlock
    | CertificationsBlock
    | SolutionOverviewBlock
    | FaqBlock
    | WorkflowBlock
    | ContactFormBlock
    | OfficeMapBlock
    | CtaBlock
    | LayoutSectionBlock
    | BadgeElement
    | HeadingElement
    | ParagraphElement
    | ImageElement
    | ButtonElement
    | CardElement
    | SpacerElement
  )[];
  /**
   * Leave empty to use the page title & the site's default description.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant: 'home' | 'centered' | 'page';
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  background: number | Media;
  /**
   * Optional. Used on screens < 768px.
   */
  backgroundMobile?: (number | null) | Media;
  buttons?:
    | {
        label: string;
        /**
         * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
         */
        href: string;
        style?: ('fill' | 'stroke') | null;
        id?: string | null;
      }[]
    | null;
  showPartners?: boolean | null;
  showCertificates?: boolean | null;
  showScrollHint?: boolean | null;
  /**
   * Kosongkan untuk memakai semua partner yang dicentang "Tampilkan di marquee Hero".
   */
  partners?: (number | Partner)[] | null;
  partnerTooltip?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility & SEO. Leave empty for decorative images.
   */
  alt?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Shown in a card when the logo is hovered.
   */
  description?: string | null;
  /**
   * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
   */
  website?: string | null;
  showInHero?: boolean | null;
  logo: number | Media;
  /**
   * Optional. The original colour logo shown when the logo is hovered.
   */
  logoHover?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProblemShowcaseBlock".
 */
export interface ProblemShowcaseBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  /**
   * Hover or click an item to open it: its description shows and the image switches.
   */
  items?:
    | {
        icon: number | Media;
        title: string;
        description?: string | null;
        /**
         * Shown on the right while this item is active. Empty = the section image.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'problemShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoShowcaseBlock".
 */
export interface VideoShowcaseBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  poster: number | Media;
  /**
   * Optional. MP4/WebM video played right on the page when play is clicked (the poster shows before).
   */
  video?: (number | null) | Media;
  captionTitle?: string | null;
  captionDescription?: string | null;
  /**
   * Optional. External video link (e.g. YouTube), used when Video above is empty.
   */
  videoUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionHighlightsBlock".
 */
export interface SolutionHighlightsBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  featured: {
    image: number | Media;
    title: string;
    description?: string | null;
    tagsLabel?: string | null;
    tags?: string[] | null;
    button: {
      label: string;
      /**
       * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
       */
      href: string;
    };
  };
  items?:
    | {
        image: number | Media;
        title: string;
        /**
         * Shown when the card is hovered.
         */
        description?: string | null;
        /**
         * Shown on hover under the featured card’s tags label.
         */
        tags?: string[] | null;
        /**
         * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'solutionHighlights';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExpertiseBlock".
 */
export interface ExpertiseBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  stats?:
    | {
        value: number;
        /**
         * e.g. +, %, K+ Hour
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  cards?:
    | {
        image: number | Media;
        icon: number | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'expertise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  variant: 'cards' | 'values';
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  /**
   * Second image layer on top of the background.
   */
  backgroundOverlay?: (number | null) | Media;
  quote?: string | null;
  items?:
    | {
        icon: number | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadershipBlock".
 */
export interface LeadershipBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  leaders?:
    | {
        photo: number | Media;
        name: string;
        /**
         * e.g. Founder, CEO
         */
        roles?: string[] | null;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'leadership';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamStatsBlock".
 */
export interface TeamStatsBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  items?:
    | {
        value: number;
        /**
         * e.g. +, %, K+ Hour
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamStats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock".
 */
export interface PartnersBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  rowOne: (number | Partner)[];
  rowTwo?: (number | Partner)[] | null;
  showTooltip?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CertificationsBlock".
 */
export interface CertificationsBlock {
  variant: 'cards' | 'gallery';
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  /**
   * Leave empty to show all certifications in order.
   */
  items?: (number | Certification)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'certifications';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  _order?: string | null;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  icon: number | Media;
  /**
   * Optional. Full-colour logo shown when the card is hovered.
   */
  iconHover?: (number | null) | Media;
  iconShape?: ('square' | 'wide' | 'narrow') | null;
  /**
   * Optional. Without it, the certification is left out of the certificate gallery.
   */
  certificate?: (number | null) | Media;
  certificateFocus?: ('center' | 'top') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionOverviewBlock".
 */
export interface SolutionOverviewBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'solutionOverview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowBlock".
 */
export interface WorkflowBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  /**
   * Numbers (01, 02, …) follow the order automatically.
   */
  steps?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'workflow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  eyebrow?: string | null;
  title: string;
  titleMobile?: string | null;
  description?: string | null;
  descriptionMobile?: string | null;
  background?: (number | null) | Media;
  submitLabel?: string | null;
  responseNote?: string | null;
  /**
   * Options of the "Consultation Interest" dropdown.
   */
  interestOptions?: string[] | null;
  whatsappText?: string | null;
  successMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfficeMapBlock".
 */
export interface OfficeMapBlock {
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'officeMap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  variant: 'simple' | 'withMedia';
  header: {
    eyebrow?: string | null;
    /**
     * Press Enter for a new line.
     */
    title: string;
    description?: string | null;
  };
  background: number | Media;
  /**
   * Optional. Used on screens < 768px.
   */
  backgroundMobile?: (number | null) | Media;
  buttons?:
    | {
        label: string;
        /**
         * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
         */
        href: string;
        style?: ('fill' | 'stroke') | null;
        id?: string | null;
      }[]
    | null;
  media?: (number | null) | Media;
  /**
   * Optional. MP4/WebM video played right on the page (the Media image is its poster).
   */
  video?: (number | null) | Media;
  /**
   * Optional. External video link (e.g. YouTube), used when Video above is empty.
   */
  videoUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LayoutSectionBlock".
 */
export interface LayoutSectionBlock {
  columns: '1' | '2' | '3' | '4';
  verticalAlign?: ('start' | 'center') | null;
  gap?: ('sm' | 'md' | 'lg') | null;
  background?: ('dark' | 'darker' | 'gradient' | 'image') | null;
  padding?: ('sm' | 'md' | 'lg') | null;
  width?: ('narrow' | 'default' | 'wide') | null;
  backgroundImage?: (number | null) | Media;
  column1?:
    | (BadgeElement | HeadingElement | ParagraphElement | ImageElement | ButtonElement | CardElement | SpacerElement)[]
    | null;
  column2?:
    | (BadgeElement | HeadingElement | ParagraphElement | ImageElement | ButtonElement | CardElement | SpacerElement)[]
    | null;
  column3?:
    | (BadgeElement | HeadingElement | ParagraphElement | ImageElement | ButtonElement | CardElement | SpacerElement)[]
    | null;
  column4?:
    | (BadgeElement | HeadingElement | ParagraphElement | ImageElement | ButtonElement | CardElement | SpacerElement)[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'layoutSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BadgeElement".
 */
export interface BadgeElement {
  text: string;
  align?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'badge';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingElement".
 */
export interface HeadingElement {
  text: string;
  level?: ('h1' | 'h2' | 'h3' | 'h4') | null;
  size?: ('sm' | 'md' | 'lg' | 'xl') | null;
  color?: ('accent' | 'white') | null;
  align?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ParagraphElement".
 */
export interface ParagraphElement {
  text: string;
  size?: ('sm' | 'base' | 'lg') | null;
  tone?: ('default' | 'muted') | null;
  align?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'paragraph';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageElement".
 */
export interface ImageElement {
  image: number | Media;
  aspect?: ('video' | 'landscape' | 'square' | 'portrait') | null;
  framed?: boolean | null;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonElement".
 */
export interface ButtonElement {
  label: string;
  /**
   * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
   */
  href: string;
  style?: ('fill' | 'stroke') | null;
  align?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardElement".
 */
export interface CardElement {
  icon?: (number | null) | Media;
  title: string;
  description?: string | null;
  /**
   * Optional. Makes the card clickable.
   */
  href?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerElement".
 */
export interface SpacerElement {
  size?: ('sm' | 'md' | 'lg' | 'xl') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * Each category has a detail page at /solution/<slug>. Drag to reorder the tabs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-categories".
 */
export interface SolutionCategory {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * URL part. Lowercase letters, numbers and "-". Generated from the title when empty.
   */
  slug: string;
  /**
   * Turn off while the detail content is not ready (the page returns 404).
   */
  hasDetailPage?: boolean | null;
  hero?: {
    /**
     * Empty = the category title.
     */
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    recommendedFor?: string[] | null;
  };
  challenges?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    items?:
      | {
          icon: 'downtime' | 'cost' | 'error' | 'inconsistent';
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  showcase?: {
    /**
     * Tab background; also the poster of the background video below.
     */
    background?: (number | null) | Media;
    /**
     * Optional. Background video (muted, looping). MP4 720p, ~10 s, < 4 MB.
     */
    backgroundVideo?: (number | null) | Media;
    /**
     * Brochure PDF. Empty = the button links to the contact page.
     */
    brochure?: (number | null) | Media;
    tabs?:
      | {
          name: string;
          description?: string | null;
          tags?: string[] | null;
          /**
           * Optional. Background video for this tab (replaces the shared one). MP4 1080p, ~25 s, no audio, ≤ 15 MB.
           */
          video?: (number | null) | Media;
          /**
           * Optional. Lighter version for phones: MP4 720p, ≤ 4 MB. Empty = the desktop video.
           */
          videoMobile?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    background?: (number | null) | Media;
    buttonLabel?: string | null;
    /**
     * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
     */
    buttonHref: string;
  };
  /**
   * Leave empty to use the page title & the site's default description.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Product cards in Solution Overview and the mega menu (each category's first product is the big card). Drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Short description: "Our Solutions" mega menu and the card on hover.
   */
  summary?: string | null;
  /**
   * "Recommended For" chips, shown on the card on hover.
   */
  tags?: string[] | null;
  category: number | SolutionCategory;
  /**
   * Clicking the card opens the category page at this Showcase tab.
   */
  showcaseTab?: string | null;
  /**
   * URL part. Lowercase letters, numbers and "-". Generated from the title when empty.
   */
  slug: string;
  image: number | Media;
  imageMobile?: (number | null) | Media;
  layout?: {
    wide?: boolean | null;
    largeTitle?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  status?: ('new' | 'in-progress' | 'done' | 'spam') | null;
  fullName: string;
  organization: string;
  email: string;
  phone: string;
  interest?: string | null;
  message?: string | null;
  internalNotes?: string | null;
  meta?: {
    ip?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  totpEnabled?: boolean | null;
  twoFactor?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  name?: string | null;
  /**
   * Admin: manage users & settings. Editor: content only.
   */
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * History of changes & logins. Cannot be edited or deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete' | 'login' | 'security';
  resource: string;
  documentId?: string | null;
  changedFields?: string[] | null;
  user?: (number | null) | User;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'solution-categories';
        value: number | SolutionCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        problemShowcase?: T | ProblemShowcaseBlockSelect<T>;
        videoShowcase?: T | VideoShowcaseBlockSelect<T>;
        solutionHighlights?: T | SolutionHighlightsBlockSelect<T>;
        expertise?: T | ExpertiseBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        leadership?: T | LeadershipBlockSelect<T>;
        teamStats?: T | TeamStatsBlockSelect<T>;
        partners?: T | PartnersBlockSelect<T>;
        certifications?: T | CertificationsBlockSelect<T>;
        solutionOverview?: T | SolutionOverviewBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        workflow?: T | WorkflowBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        officeMap?: T | OfficeMapBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        layoutSection?: T | LayoutSectionBlockSelect<T>;
        badge?: T | BadgeElementSelect<T>;
        heading?: T | HeadingElementSelect<T>;
        paragraph?: T | ParagraphElementSelect<T>;
        image?: T | ImageElementSelect<T>;
        button?: T | ButtonElementSelect<T>;
        card?: T | CardElementSelect<T>;
        spacer?: T | SpacerElementSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  title?: T;
  description?: T;
  background?: T;
  backgroundMobile?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  showPartners?: T;
  showCertificates?: T;
  showScrollHint?: T;
  partners?: T;
  partnerTooltip?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProblemShowcaseBlock_select".
 */
export interface ProblemShowcaseBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoShowcaseBlock_select".
 */
export interface VideoShowcaseBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  poster?: T;
  video?: T;
  captionTitle?: T;
  captionDescription?: T;
  videoUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionHighlightsBlock_select".
 */
export interface SolutionHighlightsBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  featured?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        tagsLabel?: T;
        tags?: T;
        button?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  items?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        tags?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ExpertiseBlock_select".
 */
export interface ExpertiseBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  cards?:
    | T
    | {
        image?: T;
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  variant?: T;
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  backgroundOverlay?: T;
  quote?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadershipBlock_select".
 */
export interface LeadershipBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  leaders?:
    | T
    | {
        photo?: T;
        name?: T;
        roles?: T;
        bio?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamStatsBlock_select".
 */
export interface TeamStatsBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  items?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock_select".
 */
export interface PartnersBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  rowOne?: T;
  rowTwo?: T;
  showTooltip?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CertificationsBlock_select".
 */
export interface CertificationsBlockSelect<T extends boolean = true> {
  variant?: T;
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SolutionOverviewBlock_select".
 */
export interface SolutionOverviewBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowBlock_select".
 */
export interface WorkflowBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleMobile?: T;
  description?: T;
  descriptionMobile?: T;
  background?: T;
  submitLabel?: T;
  responseNote?: T;
  interestOptions?: T;
  whatsappText?: T;
  successMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfficeMapBlock_select".
 */
export interface OfficeMapBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  variant?: T;
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  background?: T;
  backgroundMobile?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  media?: T;
  video?: T;
  videoUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LayoutSectionBlock_select".
 */
export interface LayoutSectionBlockSelect<T extends boolean = true> {
  columns?: T;
  verticalAlign?: T;
  gap?: T;
  background?: T;
  padding?: T;
  width?: T;
  backgroundImage?: T;
  column1?:
    | T
    | {
        badge?: T | BadgeElementSelect<T>;
        heading?: T | HeadingElementSelect<T>;
        paragraph?: T | ParagraphElementSelect<T>;
        image?: T | ImageElementSelect<T>;
        button?: T | ButtonElementSelect<T>;
        card?: T | CardElementSelect<T>;
        spacer?: T | SpacerElementSelect<T>;
      };
  column2?:
    | T
    | {
        badge?: T | BadgeElementSelect<T>;
        heading?: T | HeadingElementSelect<T>;
        paragraph?: T | ParagraphElementSelect<T>;
        image?: T | ImageElementSelect<T>;
        button?: T | ButtonElementSelect<T>;
        card?: T | CardElementSelect<T>;
        spacer?: T | SpacerElementSelect<T>;
      };
  column3?:
    | T
    | {
        badge?: T | BadgeElementSelect<T>;
        heading?: T | HeadingElementSelect<T>;
        paragraph?: T | ParagraphElementSelect<T>;
        image?: T | ImageElementSelect<T>;
        button?: T | ButtonElementSelect<T>;
        card?: T | CardElementSelect<T>;
        spacer?: T | SpacerElementSelect<T>;
      };
  column4?:
    | T
    | {
        badge?: T | BadgeElementSelect<T>;
        heading?: T | HeadingElementSelect<T>;
        paragraph?: T | ParagraphElementSelect<T>;
        image?: T | ImageElementSelect<T>;
        button?: T | ButtonElementSelect<T>;
        card?: T | CardElementSelect<T>;
        spacer?: T | SpacerElementSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BadgeElement_select".
 */
export interface BadgeElementSelect<T extends boolean = true> {
  text?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingElement_select".
 */
export interface HeadingElementSelect<T extends boolean = true> {
  text?: T;
  level?: T;
  size?: T;
  color?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ParagraphElement_select".
 */
export interface ParagraphElementSelect<T extends boolean = true> {
  text?: T;
  size?: T;
  tone?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageElement_select".
 */
export interface ImageElementSelect<T extends boolean = true> {
  image?: T;
  aspect?: T;
  framed?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonElement_select".
 */
export interface ButtonElementSelect<T extends boolean = true> {
  label?: T;
  href?: T;
  style?: T;
  align?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardElement_select".
 */
export interface CardElementSelect<T extends boolean = true> {
  icon?: T;
  title?: T;
  description?: T;
  href?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerElement_select".
 */
export interface SpacerElementSelect<T extends boolean = true> {
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  description?: T;
  website?: T;
  showInHero?: T;
  logo?: T;
  logoHover?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  icon?: T;
  iconHover?: T;
  iconShape?: T;
  certificate?: T;
  certificateFocus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-categories_select".
 */
export interface SolutionCategoriesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  hasDetailPage?: T;
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        recommendedFor?: T;
      };
  challenges?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  showcase?:
    | T
    | {
        background?: T;
        backgroundVideo?: T;
        brochure?: T;
        tabs?:
          | T
          | {
              name?: T;
              description?: T;
              tags?: T;
              video?: T;
              videoMobile?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        background?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  summary?: T;
  tags?: T;
  category?: T;
  showcaseTab?: T;
  slug?: T;
  image?: T;
  imageMobile?: T;
  layout?:
    | T
    | {
        wide?: T;
        largeTitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  status?: T;
  fullName?: T;
  organization?: T;
  email?: T;
  phone?: T;
  interest?: T;
  message?: T;
  internalNotes?: T;
  meta?:
    | T
    | {
        ip?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  totpEnabled?: T;
  twoFactor?: T;
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  resource?: T;
  documentId?: T;
  changedFields?: T;
  user?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription: string;
  logo: number | Media;
  contact: {
    /**
     * Full address (shown on the website map).
     */
    address: string;
    /**
     * Filled in from the map.
     */
    latitude?: number | null;
    /**
     * Filled in from the map.
     */
    longitude?: number | null;
    /**
     * Short version for the footer. Enter = new line.
     */
    shortAddress?: string | null;
    email: string;
    /**
     * Display format, e.g. 021 2696 1651
     */
    phone: string;
    /**
     * Number visitors reach when they click WhatsApp. You can type 0812…, +62 812… or 62812…
     */
    whatsappNumber?: string | null;
    /**
     * Optional. Text already typed in when the chat opens.
     */
    whatsappMessage?: string | null;
  };
  socials?:
    | {
        /**
         * The icon follows the platform.
         */
        platform: 'facebook' | 'instagram' | 'linkedin' | 'tiktok' | 'youtube' | 'x' | 'whatsapp' | 'other';
        label: string;
        /**
         * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
         */
        url: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * The mega menu is filled automatically from Solution Categories & Products.
   */
  solutionsLabel?: string | null;
  solutionLinks?:
    | {
        label: string;
        /**
         * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
         */
        href: string;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  featured: {
    title: string;
    description?: string | null;
    image: number | Media;
    /**
     * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
     */
    href: string;
  };
  cards?:
    | {
        title: string;
        description?: string | null;
        image: number | Media;
        /**
         * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        /**
         * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Extra link choices for the page editor (e.g. a section #faq, an external site), grouped by page. Pages and solution pages are listed automatically.
   */
  linkLibrary?:
    | {
        group: string;
        links?:
          | {
              label: string;
              /**
               * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
               */
              target: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    /**
     * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
     */
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Address, email, phone & social media are set in Site Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Pick a page, or "Other" for your own URL (/contact, #faq, https://…).
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Use {year} for the current year.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  contact?:
    | T
    | {
        address?: T;
        latitude?: T;
        longitude?: T;
        shortAddress?: T;
        email?: T;
        phone?: T;
        whatsappNumber?: T;
        whatsappMessage?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  solutionsLabel?: T;
  solutionLinks?:
    | T
    | {
        label?: T;
        href?: T;
        highlight?: T;
        id?: T;
      };
  featured?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        href?: T;
      };
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        href?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  linkLibrary?:
    | T
    | {
        group?: T;
        links?:
          | T
          | {
              label?: T;
              target?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}